hide-cursor-when-typing = false
ignore-selection-foreground-color = false
padding-x = 0
# setting it to [0, -3] fixes the annoying void bar that appears at the bottom of any tui program
padding-y = [0, -3]
line-height = 1.0
env-vars = []
use-fork = false
confirm-before-quit = false
# theme = "dracula"

[cursor]
shape = "block"
blinking = true
blinking-interval = 800

[editor]
program = "nvim"
args = []

[window]
# width = 600
# height = 400
opacity = 1.0
blur = false
mode = "windowed"       # ("windowed", "maximized", "fullscreen")
decorations = "enabled" # ("enabled", "disabled", "transparent", "buttonless")

[renderer]
performance = "high"             # (low, high)
backend = "automatic"            # (automatic, gl, vulkan, dx12, metal)
disable-unfocused-render = false # disable renderer processes while Rio is unfocused.
level = 1                        # Higher the level more rendering features and computations
# list of paths to RetroArch slang shaders. Might not work with OpenGL.
filters = []


# [keyboard]
# use-kitty-keyboard-protocol = false
# disable-ctlseqs-alt = false

[fonts]
family = "JetBrainsMono Nerd Font"
size = 16
# hinting = false

[scroll]
multiplier = 3.0
divider = 1.0

[navigation]
mode = "Bookmark"       # (Bookmark, BottomTab, TopTab, Plain)
clickable = false       # self explanatory
hide-if-single = true   # self explanatory
use-current-path = true # Note: requires `use-fork` to be set to false
# Set a specific color for the tab whenever a specific program is running, or in a specific directory.
color-automation = []

[shell]
program = "fish"
args = ["--login"]

[developer]
log-level = "OFF"
enable-log-file = false
